apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis-pri
      image: redis:5.0.5
      command:
        - redis-server
        - "/redis-master/redis.conf" 
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
          memory: "128Mi"
      volumeMounts:
        - mountPath: /redis-master-data
          name: redis-pri-data
        - mountPath: /redis-master
          name: redis-pri-config         
    - name: redis-cache
      image: redis:5.0.5
      command:
        - redis-server
        - "/redis-master/redis.conf" 
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6380
      resources:
        limits:
          cpu: "0.1"
          memory: "128Mi"
      volumeMounts:
        - mountPath: /redis-master-data
          name: redis-cache-data
        - mountPath: /redis-master
          name: redis-cache-config          
  volumes:
    - name: redis-pri-data
      emptyDir: {}
    - name: redis-cache-data
      emptyDir: {}
    - name: redis-pri-config
      configMap:
        name: redis-pri-config
        items:
        - key: redis-pri.conf
          path: redis.conf
    - name: redis-cache-config
      configMap:
        name: redis-cache-config
        items:
        - key: redis-cache.conf
          path: redis.conf
